Repository QuartetTeam/license-hunter-be, pull requests merged in 2025-02, with the labels that each got.

#2 예외처리 구현
  .gitattributes
  .github/pull_request_template.md
  .gitignore
  .husky/prepare-commit-msg
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  package-lock.json
  package.json
  settings.gradle
  src/main/java/quartet/server/ServerApplication.java
  src/main/java/quartet/server/api/common/response/QuartetResponse.java
  src/main/java/quartet/server/api/test/controller/TestController.java
  src/main/java/quartet/server/api/test/dto/resquest/TestRequest.java
  src/main/java/quartet/server/core/code/CommonCode.java
  src/main/java/quartet/server/core/code/ErrorCode.java
  src/main/java/quartet/server/core/code/SuccessCode.java
  src/main/java/quartet/server/core/exception/CommonException.java
  src/main/java/quartet/server/core/exception/GlobalExceptionHandler.java
  src/main/java/quartet/server/core/exception/NotFoundException.java
  src/main/resources/application.yml
  src/test/java/quartet/server/ServerApplicationTests.java
Labels: enhancement

#9 Base Entity 생성 및 엔티티 클래스 작성 규칙
  src/main/java/quartet/server/core/config/JpaConfig.java
  src/main/java/quartet/server/core/entity/BaseAuditEntity.java
  src/main/java/quartet/server/core/entity/BaseTimeEntity.java
  src/main/java/quartet/server/core/entity/IdentifiableEntity.java
  src/main/java/quartet/server/entity/certification/Authority.java
  src/main/java/quartet/server/entity/certification/Certification.java
Labels: 📂 etc

#13 Calendar 엔티티 & Mail 관련 엔티티 추가
  src/main/java/quartet/server/domain/calender/model/Calendar.java
  src/main/java/quartet/server/domain/certification/model/Authority.java
  src/main/java/quartet/server/domain/certification/model/Certification.java
  src/main/java/quartet/server/domain/mail/model/MailAlarm.java
  src/main/java/quartet/server/domain/mail/model/MailAlarmStatus.java
Labels: ✨ feature, ♻️ refactor

#18 카테고리 관련 초기설정
  src/main/java/quartet/server/core/code/CategoryErrorCode.java
  src/main/java/quartet/server/domain/category/exception/CategoryException.java
  src/main/java/quartet/server/domain/category/exception/CategoryNotFoundException.java
  src/main/java/quartet/server/domain/category/model/Category.java
  src/main/java/quartet/server/domain/category/repository/CategoryRepository.java
Labels: ✨ feature

#21 Jira - GitHub issue 연동
  .github/ISSUE_TEMPLATE/issue_template.yml
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/workflows/close-jira-issue.yml
  .github/workflows/create-jira-issue.yml
  .husky/commit-msg
  .husky/prepare-commit-msg
  package.json
Labels: ⚙️ infra

#20 Member 관련 초기 설정
  src/main/java/quartet/server/core/code/AuthErrorCode.java
  src/main/java/quartet/server/domain/auth/exception/AccessTokenException.java
  src/main/java/quartet/server/domain/auth/exception/AuthException.java
  src/main/java/quartet/server/domain/auth/exception/RefreshTokenException.java
  src/main/java/quartet/server/domain/auth/model/RefreshToken.java
  src/main/java/quartet/server/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/quartet/server/domain/member/exception/MemberException.java
  src/main/java/quartet/server/domain/member/exception/MemberNotFoundException.java
  src/main/java/quartet/server/domain/member/model/Member.java
  src/main/java/quartet/server/domain/member/model/MemberCategory.java
  src/main/java/quartet/server/domain/member/repository/MemberRepository.java
Labels: ✨ feature

#26 final 키워드 추가 및 enum 클래스 구조 변경
  src/main/java/quartet/server/domain/certification/model/Authority.java
  src/main/java/quartet/server/domain/certification/model/Certification.java
  src/main/java/quartet/server/domain/certification/model/CertificationDescription.java
  src/main/java/quartet/server/domain/certification/model/CertificationExamDetail.java
  src/main/java/quartet/server/domain/certification/model/CertificationPassCriteria.java
  src/main/java/quartet/server/domain/certification/model/CertificationSchedule.java
  src/main/java/quartet/server/domain/certification/model/CertificationViewLog.java
  src/main/java/quartet/server/domain/certification/type/ExamType.java
  src/main/java/quartet/server/domain/certification/type/ProblemType.java
  src/main/java/quartet/server/domain/certification/type/ScheduleType.java
Labels: ♻️ refactor

#29 QUAR-16-BE-member-cateogry-클래스-수정
  src/main/java/quartet/server/domain/category/model/Category.java
  src/main/java/quartet/server/domain/member/model/Member.java
  src/main/java/quartet/server/domain/member/model/MemberCategory.java
Labels: ♻️ refactor

#34 application-yml 파일 환경 분리
  src/main/resources/application-develop.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: ⚙️ infra

#45 [QUAR-19] 임시 테스트 실행 환경
  build.gradle
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 📂 etc
