Repository QuartetTeam/license-hunter-be, pull requests merged in 2025-03, with the labels that each got.

#49 Calendar 통합테스트 및 단위테스트 추가
  .gitignore
  src/main/java/quartet/server/api/calendar/controller/CalendarController.java
  src/main/java/quartet/server/api/calendar/dto/response/CalendarResponse.java
  src/main/java/quartet/server/api/calendar/query/CalendarQueryRepository.java
  src/main/java/quartet/server/api/calendar/service/CalendarService.java
  src/main/java/quartet/server/api/common/response/ApiResponse.java
  src/main/java/quartet/server/api/dummy/DataGeneratorController.java
  src/main/java/quartet/server/api/dummy/DataGeneratorService.java
  src/main/java/quartet/server/core/advice/ApiResponseAdvice.java
  src/main/java/quartet/server/core/advice/GlobalExceptionHandler.java
  src/test/java/quartet/server/api/calendar/controller/CalendarControllerTest.java
  src/test/java/quartet/server/api/calendar/fixture/CalendarFixture.java
  src/test/java/quartet/server/api/calendar/service/CalendarServiceTest.java
Labels: 🐛 bug, ✅ test, ♻️ refactor

#52 더미 데이터 관련 API 삭제
  src/main/java/quartet/server/api/dummy/DataGeneratorController.java
  src/main/java/quartet/server/api/dummy/DataGeneratorService.java
Labels: 🚑 hotfix

#56 추천 자격증 조회 api 구현
  src/main/java/quartet/server/api/certification/CertificationController.java
  src/main/java/quartet/server/api/certification/CertificationService.java
  src/main/java/quartet/server/api/certification/controller/CertificationController.java
  src/main/java/quartet/server/api/certification/dto/response/CertificationCategoriesResponse.java
  src/main/java/quartet/server/api/certification/dto/response/CertificationResponse.java
  src/main/java/quartet/server/api/certification/dto/response/CertificationsByCategoryResponse.java
  src/main/java/quartet/server/api/certification/query/CategoryQueryRepository.java
  src/main/java/quartet/server/api/certification/query/CertificationQueryRepository.java
  src/main/java/quartet/server/api/certification/service/CertificationService.java
  src/main/java/quartet/server/core/utils/RandomGenerator.java
  src/main/java/quartet/server/core/utils/ThreadLocalRandomGenerator.java
  src/main/java/quartet/server/domain/member/repository/MemberCategoryRepository.java
  src/test/java/quartet/server/api/certification/CertificationControllerTest.java
  src/test/java/quartet/server/api/certification/CertificationServiceTest.java
  src/test/java/quartet/server/utils/fixture/Certification/CertificationCategoryFixture.java
  src/test/java/quartet/server/utils/fixture/Certification/CertificationFixture.java
Labels: ✨ feature

#61 캘린더 조회시 scheduleType, examType을 한글로 변경 및 ScheduleType 컬럼 변경
  src/main/java/quartet/server/api/calendar/controller/CalendarController.java
  src/main/java/quartet/server/api/calendar/dto/response/CalendarResponse.java
  src/main/java/quartet/server/api/calendar/query/CalendarQueryRepository.java
  src/main/java/quartet/server/api/calendar/service/CalendarService.java
  src/main/java/quartet/server/api/certification/query/CertificationQueryRepository.java
  src/main/java/quartet/server/domain/certification/type/ScheduleType.java
  src/test/java/quartet/server/api/calendar/controller/CalendarControllerTest.java
  src/test/java/quartet/server/api/calendar/fixture/CalendarFixture.java
  src/test/java/quartet/server/api/calendar/service/CalendarServiceTest.java
  src/test/java/quartet/server/utils/fixture/Certification/CertificationFixture.java
Labels: ✨ feature
