Repository QuartetTeam/license-hunter-be, pull requests merged in 2025-05, with the labels that each got.

#97 마이페이지 구현
  src/main/java/quartet/server/api/auth/service/CustomOAuth2UserService.java
  src/main/java/quartet/server/api/member/controller/MemberController.java
  src/main/java/quartet/server/api/member/dto/request/UpdateEmailRequest.java
  src/main/java/quartet/server/api/member/dto/request/UpdateInterestsRequest.java
  src/main/java/quartet/server/api/member/dto/request/UpdateNicknameRequest.java
  src/main/java/quartet/server/api/member/dto/response/MemberEmailResponse.java
  src/main/java/quartet/server/api/member/dto/response/MemberInfoResponse.java
  src/main/java/quartet/server/api/member/dto/response/MemberInterestResponse.java
  src/main/java/quartet/server/api/member/dto/response/MemberNicknameResponse.java
  src/main/java/quartet/server/api/member/dto/response/MemberProfileImageResponse.java
  src/main/java/quartet/server/api/member/service/MemberService.java
  src/main/java/quartet/server/core/code/CategoryErrorCode.java
  src/main/java/quartet/server/domain/calender/exception/CategorySelectionLimitExceededException.java
  src/main/java/quartet/server/domain/category/model/MainCategory.java
  src/main/java/quartet/server/domain/image/exception/UnsupportedImageFormatException.java
  src/main/java/quartet/server/domain/image/service/ImageService.java
  src/main/java/quartet/server/domain/member/exception/MemberException.java
  src/main/java/quartet/server/domain/member/model/Member.java
  src/main/java/quartet/server/domain/member/model/MemberCategory.java
  src/main/java/quartet/server/domain/member/repository/MemberRepository.java
Labels: ✨ feature

#102 마이페이지 코드 수정
  src/main/java/quartet/server/api/auth/service/CustomOAuth2UserService.java
  src/main/java/quartet/server/api/member/controller/MemberController.java
  src/main/java/quartet/server/api/member/service/MemberService.java
  src/main/java/quartet/server/domain/calender/repository/CalendarRepository.java
  src/main/java/quartet/server/domain/mail/repository/MailingRepository.java
  src/main/java/quartet/server/domain/member/model/Member.java
  src/main/java/quartet/server/domain/member/repository/MemberCategoryRepository.java
  src/test/java/quartet/server/api/member/fixture/MemberFixture.java
Labels: 🐛 bug

#107 소셜로그인 성공시 리다이렉트 url 변경
  src/main/java/quartet/server/core/security/handler/OauthLoginSuccessHandler.java
Labels: 🐛 bug

#111 memberId 임시 설정 @AuthenticationPrincipal로 변경
  src/main/java/quartet/server/api/calendar/controller/CalendarController.java
  src/main/java/quartet/server/api/example/controller/ExampleController.java
  src/main/java/quartet/server/api/example/dto/resquest/ExampleRequest.java
  src/main/java/quartet/server/api/mail/controller/MailingController.java
  src/main/java/quartet/server/core/advice/GlobalExceptionHandler.java
  src/main/java/quartet/server/domain/example/exception/ExampleException.java
  src/main/java/quartet/server/domain/example/exception/ExampleNotFoundException.java
Labels: ✨ feature

#120 Security Config 설정 변경
  src/main/java/quartet/server/core/config/SecurityConfig.java
Labels: 🐛 bug

#121 날짜 타입 변경
  src/main/java/quartet/server/api/calendar/dto/response/CalendarResponse.java
  src/main/java/quartet/server/api/calendar/query/CalendarQueryRepository.java
  src/main/java/quartet/server/api/calendar/service/CalendarService.java
  src/main/java/quartet/server/api/mail/controller/MailingController.java
  src/main/java/quartet/server/api/mail/dto/response/ApplicationMailProjection.java
  src/main/java/quartet/server/api/mail/dto/response/ApplicationMailResponse.java
  src/main/java/quartet/server/api/mail/dto/response/ExamMailResponse.java
  src/main/java/quartet/server/api/mail/dto/response/MailingResponse.java
  src/main/java/quartet/server/api/mail/query/MailingQueryRepository.java
  src/main/java/quartet/server/api/mail/service/MailingScheduleService.java
  src/main/java/quartet/server/core/entity/BaseTimeEntity.java
  src/main/java/quartet/server/core/utils/DateUtils.java
  src/main/java/quartet/server/domain/certification/model/CertificationSchedule.java
  src/test/java/quartet/server/api/calendar/fixture/CalendarFixture.java
  src/test/java/quartet/server/api/calendar/service/CalendarServiceTest.java
  src/test/java/quartet/server/api/mail/fixture/MailingFixture.java
  src/test/java/quartet/server/api/mail/service/MailingServiceTest.java
Labels: ♻️ refactor

#122 Feature/quar 69 get all certifications
  src/main/java/quartet/server/api/certification/controller/CertificationController.java
  src/main/java/quartet/server/api/certification/dto/response/CertificationResponse.java
  src/main/java/quartet/server/api/certification/dto/response/CertificationSearchResponse.java
  src/main/java/quartet/server/api/certification/dto/response/CertificationsByCategoryResponse.java
  src/main/java/quartet/server/api/certification/query/CategoryQueryRepository.java
  src/main/java/quartet/server/api/certification/query/CertificationQueryRepository.java
  src/main/java/quartet/server/api/certification/service/CertificationService.java
  src/main/java/quartet/server/domain/certification/model/CertificationViewLog.java
  src/test/java/quartet/server/api/certification/controller/CertificationControllerTest.java
  src/test/java/quartet/server/api/certification/service/CertificationServiceTest.java
  src/test/java/quartet/server/utils/fixture/Certification/CertificationFixture.java
Labels: ✨ feature

#124 메일링 조회 api 정렬 방식 변경
  src/main/java/quartet/server/api/mail/controller/EmailTestController.java
  src/main/java/quartet/server/api/mail/query/MailingQueryRepository.java
Labels: ✨ feature

#126 google 소셜로그인 시 닉네임을 이메일로부터 추출
  src/main/java/quartet/server/api/auth/dto/GoogleResponse.java
Labels: ✨ feature

#128 Calendar 삭제 api 오류 수정
  src/main/java/quartet/server/api/calendar/controller/CalendarController.java
Labels: 🐛 bug

#130 가상스레드를 이용한 메일링 스케줄링 구현
  src/main/java/quartet/server/api/mail/service/EmailProcessingService.java
  src/main/java/quartet/server/api/mail/service/MailingScheduleService.java
  src/main/java/quartet/server/core/config/ScheduleConfig.java
  src/main/resources/templates/email/exam-day.html
Labels: 🐛 bug, ✨ feature

#133 Fix: 임시조치
  src/main/java/quartet/server/api/certification/controller/CertificationController.java
  src/main/java/quartet/server/api/certification/service/CertificationService.java
Labels: 📂 etc
