Repository QuartetTeam/license-hunter-be, pull requests merged in 2025-04, with the labels that each got.

#66 ERD 수정 사항 반영
  src/main/java/quartet/server/api/calendar/dto/response/CalendarResponse.java
  src/main/java/quartet/server/api/calendar/query/CalendarQueryRepository.java
  src/main/java/quartet/server/api/certification/controller/CertificationController.java
  src/main/java/quartet/server/api/certification/dto/response/CertificationCategoriesResponse.java
  src/main/java/quartet/server/api/certification/dto/response/CertificationResponse.java
  src/main/java/quartet/server/api/certification/dto/response/MainCategoryResponse.java
  src/main/java/quartet/server/api/certification/dto/response/SubCategoryResponse.java
  src/main/java/quartet/server/api/certification/query/CategoryQueryRepository.java
  src/main/java/quartet/server/api/certification/query/CertificationQueryRepository.java
  src/main/java/quartet/server/api/certification/service/CertificationService.java
  src/main/java/quartet/server/domain/category/model/Category.java
  src/main/java/quartet/server/domain/category/model/MainCategory.java
  src/main/java/quartet/server/domain/category/model/SubCategory.java
  src/main/java/quartet/server/domain/category/repository/CategoryRepository.java
  src/main/java/quartet/server/domain/category/repository/MainCategoryRepository.java
  src/main/java/quartet/server/domain/category/repository/SubCategoryRepository.java
  src/main/java/quartet/server/domain/certification/model/Certification.java
  src/main/java/quartet/server/domain/certification/model/CertificationDescription.java
  src/main/java/quartet/server/domain/certification/model/CertificationQualification.java
  src/main/java/quartet/server/domain/certification/model/CertificationSchedule.java
  src/main/java/quartet/server/domain/certification/model/TechnicalQualification.java
  src/main/java/quartet/server/domain/certification/repository/CertificationQualificationRepository.java
  src/main/java/quartet/server/domain/certification/repository/TechnicalQualificationRepository.java
  src/main/java/quartet/server/domain/certification/type/QualificationType.java
  src/main/java/quartet/server/domain/certification/type/TechnicalGradeType.java
  src/main/java/quartet/server/domain/member/model/MemberCategory.java
  src/main/resources/sql/certification_init.sql
  src/test/java/quartet/server/api/calendar/fixture/CalendarFixture.java
  src/test/java/quartet/server/api/certification/CertificationServiceTest.java
  src/test/java/quartet/server/api/certification/controller/CertificationControllerTest.java
  src/test/java/quartet/server/api/certification/service/CertificationServiceTest.java
  src/test/java/quartet/server/api/mail/fixture/MailingFixture.java
  src/test/java/quartet/server/utils/fixture/Certification/CertificationCategoryFixture.java
  src/test/java/quartet/server/utils/fixture/Certification/CertificationFixture.java
Labels: ♻️ refactor

#69 WindowOS에서 커밋 메시지 오류 해결
  .husky/commit-msg
  .husky/commit-msg.js
  .husky/prepare-commit-msg
  .husky/prepare-commit-msg.js
  package-lock.json
  package.json
Labels: 🐛 bug

#67 [QUAR-17] 로그인 기능 구현
  build.gradle
  package-lock.json
  src/main/java/quartet/server/api/auth/controller/OAuth2Controller.java
  src/main/java/quartet/server/api/auth/controller/ReissueController.java
  src/main/java/quartet/server/api/auth/dto/CustomOAuth2User.java
  src/main/java/quartet/server/api/auth/dto/GoogleResponse.java
  src/main/java/quartet/server/api/auth/dto/KakaoResponse.java
  src/main/java/quartet/server/api/auth/dto/NaverResponse.java
  src/main/java/quartet/server/api/auth/dto/OAuth2Response.java
  src/main/java/quartet/server/api/auth/service/CustomOAuth2UserService.java
  src/main/java/quartet/server/api/auth/service/OAuth2JwtHeaderService.java
  src/main/java/quartet/server/api/auth/service/ReissueService.java
  src/main/java/quartet/server/core/config/SecurityConfig.java
  src/main/java/quartet/server/core/security/filter/CustomLogoutFilter.java
  src/main/java/quartet/server/core/security/filter/JwtAuthenticationFilter.java
  src/main/java/quartet/server/core/security/jwt/JwtUtil.java
  src/main/java/quartet/server/core/security/ouath2/OauthLoginSuccessHandler.java
  src/main/java/quartet/server/core/security/userDetails/CustomUserDetails.java
  src/main/java/quartet/server/domain/auth/model/RefreshToken.java
  src/main/java/quartet/server/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/quartet/server/domain/member/repository/MemberRepository.java
  src/main/resources/application-develop.yml
  src/main/resources/application-local.yml
Labels: ✨ feature

#71 AWS S3를 이용한 이미지 로직 구현
  build.gradle
  src/main/java/quartet/server/core/advice/GlobalExceptionHandler.java
  src/main/java/quartet/server/core/code/CommonErrorCode.java
  src/main/java/quartet/server/core/code/ImageErrorCode.java
  src/main/java/quartet/server/core/config/S3Config.java
  src/main/java/quartet/server/core/health/S3HealthIndicator.java
  src/main/java/quartet/server/domain/image/exception/ImageDeletionFailedException.java
  src/main/java/quartet/server/domain/image/exception/ImageException.java
  src/main/java/quartet/server/domain/image/exception/ImageUploadFailedException.java
  src/main/java/quartet/server/domain/image/exception/InvalidImageUrlFormatException.java
  src/main/java/quartet/server/domain/image/service/ImageService.java
  src/main/resources/application-develop.yml
  src/main/resources/application-local.yml
  src/test/java/quartet/server/api/image/fixture/ImageFixture.java
  src/test/java/quartet/server/api/image/service/ImageServiceTest.java
Labels: ✨ feature, ⚙️ infra

#80 null값 처리 로직 추가
  src/main/java/quartet/server/api/certification/dto/response/CertificationSearchResponse.java
Labels: ♻️ refactor

#88 소셜로그인 관련 코드 수정
  src/main/java/quartet/server/api/auth/service/OAuth2JwtHeaderService.java
  src/main/java/quartet/server/api/auth/service/ReissueService.java
  src/main/java/quartet/server/core/security/filter/CustomLogoutFilter.java
  src/main/java/quartet/server/core/security/ouath2/OauthLoginSuccessHandler.java
Labels: ♻️ refactor
